# Generated by Django 4.1.7 on 2023-02-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_ads_text_alter_ads_title_alter_feedback_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='text',
            field=models.CharField(default='текст статьи от 2023-02-20 13:10:57.227324', max_length=512),
        ),
        migrations.AlterField(
            model_name='ads',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(default='заголовок статьи от 2023-02-20 13:10:57.227304', max_length=64),
        ),
        migrations.AlterField(
            model_name='ads',
            name='upload',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(default='текст отклика от 2023-02-20 13:10:57.227554', max_length=256),
        ),
    ]
