# Generated by Django 4.1.7 on 2023-02-20 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_alter_ads_text_alter_ads_time_create_alter_ads_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateField(auto_created=True)),
                ('text', models.CharField(default='текст отклика от 2023-02-20 17:59:45.599904', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='ads',
            name='text',
            field=models.CharField(default='текст статьи от 2023-02-20 17:59:45.599682', max_length=512),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(default='заголовок статьи от 2023-02-20 17:59:45.599664', max_length=64),
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
        migrations.AddField(
            model_name='reply',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ads'),
        ),
        migrations.AddField(
            model_name='reply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
