# Generated by Django 4.1.7 on 2023-02-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_reply_alter_ads_text_alter_ads_title_delete_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='text',
            field=models.CharField(default='текст статьи от 2023-02-20 18:33:51.713580', max_length=512),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(default='заголовок статьи от 2023-02-20 18:33:51.713560', max_length=64),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.CharField(default='текст отклика от 2023-02-20 18:33:51.713801', max_length=256),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time_create',
            field=models.DateField(auto_now_add=True),
        ),
    ]
